# Generated by Django 3.1.4 on 2021-01-04 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esl', '0002_userevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='esl.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='registered',
            name='event',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='user',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='event',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Registered',
        ),
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
