# Generated by Django 3.1.4 on 2021-01-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esl', '0006_auto_20210104_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
