# Generated by Django 3.1.4 on 2021-01-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esl', '0007_auto_20210104_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='register_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
