# Generated by Django 3.1.4 on 2021-01-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esl', '0008_tournament_register_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='register_count',
            field=models.IntegerField(default=0),
        ),
    ]
