# Generated by Django 3.1.4 on 2021-01-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esl', '0009_auto_20210104_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AlterField(
            model_name='result',
            name='position',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
